### ISSUE TITLE
禁止游客登录的上传策略 & 修改邮箱失败

### ISSUE THREAD

**Issue by sprders** [sduoduo233/imgu2#22]
docker部署

1. 禁止游客上传后，仍然会调用上传接口，然后提示未登录，能不能改成不调用上传接口，直接提示用户未登录？比如向服务器发送空消息，测试该cookie是否有效，有效后再调用上传。
2. 修改邮箱失败，提示504（好像是这个），重复多次，每次都是失败。通过直接修改数据库才成功。

**Comment by sduoduo233** [comment]
修改邮箱失败是不是SMTP配置有问题？[docker logs](https://docs.docker.com/reference/cli/docker/container/logs/) 有报错吗？

**Comment by sduoduo233** [comment]
> 禁止游客上传后，仍然会调用上传接口，然后提示未登录，能不能改成不调用上传接口，直接提示用户未登录？比如向服务器发送空消息，测试该cookie是否有效，有效后再调用上传。

前端可以改成未登陆隐藏上传页面，但是用户依然可以绕过前端直接调用API
