### ISSUE TITLE
Docker 修改邮箱报错

### ISSUE THREAD

**Issue by xingkb** [sduoduo233/imgu2#23]
sendmail: dial failed: EOF

`time=2024-05-16T14:22:01.273Z level=ERROR msg="change email" err="sendmail: dial failed: EOF"
2024/05/16 14:22:01 "POST http://tg.nothing.com/dashboard/change-email HTTP/1.1" from 172.20.0.1:35030 - 500 0B in 17.53111255s`

**Comment by xingkb** [comment]
绑定GitHub登录也不行，有操作手册吗？
Homepage URL 写了反代的域名 tg.example.com
Authorization callback URL  http://tg.example.com/login/github/callback ?
现在配置登录提示github login is disabled

**Comment by xingkb** [comment]
> 绑定GitHub登录也不行，有操作手册吗？ Homepage URL 写了反代的域名 tg.example.com Authorization callback URL http://tg.example.com/login/github/callback ? 现在配置登录提示github login is disabled

好吧 我的问题 谁知道还要去账户设置绑定下账户啊……

**Comment by sduoduo233** [comment]
> 有操作手册吗？

~~最近有时间写一下~~

>  Homepage URL 写了反代的域名 tg.example.com
Authorization callback URL http://tg.example.com/login/github/callback ?

对

> github login is disabled

改完 oauth 登录设置要重启
